pub(crate) mod app_volume_action;
pub(crate) mod foreground_volume;
pub(crate) mod master_volume;
pub(crate) mod press_key_action;
pub(crate) mod spotify_volume;
pub(crate) mod toggle_app_audio;
pub(crate) mod toggle_foreground_audio;
pub(crate) mod toggle_master_mute;
pub(crate) mod toggle_app_media_action;
